name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List
        run: |
          pwd
          ls
      - name: Action Checkout
        uses: actions/checkout@v1
      - name: List After
        run: |
          pwd
          ls
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Mona of Ocean
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"